package com.ssw.pojo;

public class ProductSubtable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.seller_id
     *
     * @mbg.generated
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.spu
     *
     * @mbg.generated
     */
    private Integer spu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.specification_items
     *
     * @mbg.generated
     */
    private String specificationItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.default_item_id
     *
     * @mbg.generated
     */
    private String defaultItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.is_enable_spec
     *
     * @mbg.generated
     */
    private Integer isEnableSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.type_template_id
     *
     * @mbg.generated
     */
    private Integer typeTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.package_list
     *
     * @mbg.generated
     */
    private String packageList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_subtable.sale_service
     *
     * @mbg.generated
     */
    private String saleService;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.id
     *
     * @return the value of product_subtable.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.id
     *
     * @param id the value for product_subtable.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.product_id
     *
     * @return the value of product_subtable.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.product_id
     *
     * @param productId the value for product_subtable.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.seller_id
     *
     * @return the value of product_subtable.seller_id
     *
     * @mbg.generated
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.seller_id
     *
     * @param sellerId the value for product_subtable.seller_id
     *
     * @mbg.generated
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.brand_id
     *
     * @return the value of product_subtable.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.brand_id
     *
     * @param brandId the value for product_subtable.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.spu
     *
     * @return the value of product_subtable.spu
     *
     * @mbg.generated
     */
    public Integer getSpu() {
        return spu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.spu
     *
     * @param spu the value for product_subtable.spu
     *
     * @mbg.generated
     */
    public void setSpu(Integer spu) {
        this.spu = spu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.specification_items
     *
     * @return the value of product_subtable.specification_items
     *
     * @mbg.generated
     */
    public String getSpecificationItems() {
        return specificationItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.specification_items
     *
     * @param specificationItems the value for product_subtable.specification_items
     *
     * @mbg.generated
     */
    public void setSpecificationItems(String specificationItems) {
        this.specificationItems = specificationItems == null ? null : specificationItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.default_item_id
     *
     * @return the value of product_subtable.default_item_id
     *
     * @mbg.generated
     */
    public String getDefaultItemId() {
        return defaultItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.default_item_id
     *
     * @param defaultItemId the value for product_subtable.default_item_id
     *
     * @mbg.generated
     */
    public void setDefaultItemId(String defaultItemId) {
        this.defaultItemId = defaultItemId == null ? null : defaultItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.is_enable_spec
     *
     * @return the value of product_subtable.is_enable_spec
     *
     * @mbg.generated
     */
    public Integer getIsEnableSpec() {
        return isEnableSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.is_enable_spec
     *
     * @param isEnableSpec the value for product_subtable.is_enable_spec
     *
     * @mbg.generated
     */
    public void setIsEnableSpec(Integer isEnableSpec) {
        this.isEnableSpec = isEnableSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.type_template_id
     *
     * @return the value of product_subtable.type_template_id
     *
     * @mbg.generated
     */
    public Integer getTypeTemplateId() {
        return typeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.type_template_id
     *
     * @param typeTemplateId the value for product_subtable.type_template_id
     *
     * @mbg.generated
     */
    public void setTypeTemplateId(Integer typeTemplateId) {
        this.typeTemplateId = typeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.package_list
     *
     * @return the value of product_subtable.package_list
     *
     * @mbg.generated
     */
    public String getPackageList() {
        return packageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.package_list
     *
     * @param packageList the value for product_subtable.package_list
     *
     * @mbg.generated
     */
    public void setPackageList(String packageList) {
        this.packageList = packageList == null ? null : packageList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_subtable.sale_service
     *
     * @return the value of product_subtable.sale_service
     *
     * @mbg.generated
     */
    public String getSaleService() {
        return saleService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_subtable.sale_service
     *
     * @param saleService the value for product_subtable.sale_service
     *
     * @mbg.generated
     */
    public void setSaleService(String saleService) {
        this.saleService = saleService == null ? null : saleService.trim();
    }
}