package com.ssw.pojo;

public class ProductSpecification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_specification.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_specification.spec_name
     *
     * @mbg.generated
     */
    private String specName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_specification.id
     *
     * @return the value of product_specification.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_specification.id
     *
     * @param id the value for product_specification.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_specification.spec_name
     *
     * @return the value of product_specification.spec_name
     *
     * @mbg.generated
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_specification.spec_name
     *
     * @param specName the value for product_specification.spec_name
     *
     * @mbg.generated
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }
}