package com.ssw.pojo;

public class ProductBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.first_char
     *
     * @mbg.generated
     */
    private String firstChar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.id
     *
     * @return the value of product_brand.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.id
     *
     * @param id the value for product_brand.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.name
     *
     * @return the value of product_brand.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.name
     *
     * @param name the value for product_brand.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.first_char
     *
     * @return the value of product_brand.first_char
     *
     * @mbg.generated
     */
    public String getFirstChar() {
        return firstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.first_char
     *
     * @param firstChar the value for product_brand.first_char
     *
     * @mbg.generated
     */
    public void setFirstChar(String firstChar) {
        this.firstChar = firstChar == null ? null : firstChar.trim();
    }
}