package com.ssw.dao;

import com.ssw.pojo.OperateLog;
import java.util.List;

public interface OperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatelog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatelog
     *
     * @mbg.generated
     */
    int insert(OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatelog
     *
     * @mbg.generated
     */
    OperateLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatelog
     *
     * @mbg.generated
     */
    List<OperateLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operatelog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperateLog record);
}