package com.ssw.dao;

import com.ssw.pojo.ProductBrand;
import java.util.List;

public interface ProductBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int insert(ProductBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    ProductBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    List<ProductBrand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductBrand record);

    List<ProductBrand> findBrandsByNameAndId(Long id ,String name);
}