package com.ssw.dao;

import com.ssw.pojo.ProductSpecification;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification
     *
     * @mbg.generated
     */
    int insert(ProductSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification
     *
     * @mbg.generated
     */
    ProductSpecification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification
     *
     * @mbg.generated
     */
    List<ProductSpecification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSpecification record);

    /*
     * 根据规格名字和id查询规格*/
    List<ProductSpecification> findProDecsByNameAndId(@Param("specId") Long id ,
                                                      @Param("specName") String specName);
}