package com.ssw.dao;

import com.ssw.pojo.ProductSubtable;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductSubtableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_subtable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_subtable
     *
     * @mbg.generated
     */
    int insert(ProductSubtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_subtable
     *
     * @mbg.generated
     */
    ProductSubtable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_subtable
     *
     * @mbg.generated
     */
    List<ProductSubtable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_subtable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSubtable record);


    //根据商品id删除商品
    int deleteById(Integer productId);

    //根据商品id更新商品
    int updateByProId(ProductSubtable productSubtable);

    //根据商品id查询商品
    ProductSubtable selectByProId(Integer productId);

    //根据商家id查看看商品
    List<ProductSubtable> selectBySellerId(String sellerId);

    //根据商品规格查看商品
    ProductSubtable seeProDetailBySpec(@Param("spuId")Integer spuId, @Param("productSpec") String productSpec);

    //查看可兑换的商品
    List<ProductSubtable> selectConvertibleProduct(String convertibleDesc);



}