package com.ssw.dao;

import com.ssw.pojo.ProductSpecificationOption;
import java.util.List;

public interface ProductSpecificationOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification_option
     *
     * @mbg.generated
     */
    int insert(ProductSpecificationOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification_option
     *
     * @mbg.generated
     */
    ProductSpecificationOption selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification_option
     *
     * @mbg.generated
     */
    List<ProductSpecificationOption> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_specification_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSpecificationOption record);


    /*
     * 根据specid查询*/
    List<ProductSpecificationOption> selectBySpecid(Long specid);

    /*
     * 根据specid删除*/
    int deleteBatch(Long specId) ;
}