package com.ssw.dao;

import com.ssw.pojo.ProductTypeTemplate;
import java.util.List;

public interface ProductTypeTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type_template
     *
     * @mbg.generated
     */
    int insert(ProductTypeTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type_template
     *
     * @mbg.generated
     */
    ProductTypeTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type_template
     *
     * @mbg.generated
     */
    List<ProductTypeTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductTypeTemplate record);


    //通过name或id查看模板
    List<ProductTypeTemplate> findProTypeTempByNameAndId(Long id,String name);
}